services:
  kafka:
    image: redpanda/redpanda:v24.1.5
    command: ["redpanda","start","--overprovisioned","--smp","1","--reserve-memory","0M","--set","redpanda.auto_create_topics_enabled=true","--check=false"]
    ports: ["9092:9092","9644:9644"]

  ingestion:
    build: ./ingestion
    env_file: .env
    depends_on: [kafka]
    volumes:
      - ./lake:/app/lake
      - ./.data:/app/.data

  detection:
    build: ./detection
    env_file: .env
    depends_on: [ingestion]
    volumes:
      - ./lake:/app/lake
      - ./.data:/app/.data

  dashboard:
    build: ./serving
    env_file: .env
    ports: ["8501:8501"]
    depends_on: [detection]
    volumes:
      - ./lake:/app/lake
      - ./.data:/app/.data
