name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -e .[dev]
          python -m pip install "dbt-core==1.10.*" "dbt-duckdb==1.10.*" duckdb==1.1.*
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy .
      - name: Unit tests
        run: pytest -q
      - name: dbt deps
        run: dbt deps --project-dir transform/dbt
      - name: dbt seed+run+test
        env:
          DBT_PROFILES_DIR: transform/dbt
          DUCKDB_PATH: .data/logpulse.duckdb
        run: |
          mkdir -p .data
          dbt seed --project-dir transform/dbt
          dbt run --project-dir transform/dbt
          dbt test --project-dir transform/dbt
